### PR TITLE
restructure governance and about into website

### PR DESCRIPTION
**Pull request by OriolAbril**
I think that we can use this repo and this website to populate `arviz.org`
(or whatever domain we choose), then use `python/julia.arviz.org` or something similar
for each library.

I also think this structure will make the governance easier to navigate, consult and extend.
i.e. now it's quite straighforward to add a recurrent contributor section (see
https://github.com/arviz-devs/arviz/issues/1828) and link to the onboarding contributors
section to say the process is the same, only the eligibility changes.

As it also has an about section, we could also add the roadmap here or even add a blog.

### CODE REVIEW

**Comment by OriolAbril** [comment]
comment from @sethaxen: "ArviZ Julia lib uses the MIT license". We should update the references to Apache to be somehting like OSI approved license. 

Side note: this repo needs a license, the default is not "free access for everyone" only by being public on github. I'd be happy with either mit, apache or any other license specific for textual content

**Comment by OriolAbril** [comment]
> For some reason the governance site is using the ArviZ.jl logo instead of the ArviZ one.

I configured to choose between one of the two randomly at build time :sweat_smile:. 

> Also, as per our Slack discussion, we should probably drop the ArviZ.jl logo. In that case, you could use the Julia logo to link to Julia ArviZ and the Python logo to link to Python ArviZ.

This makes much more sense, thanks. I'll do that

**Comment by sethaxen** [comment]
> I configured to choose between one of the two randomly at build time 😅.

❤️‍🔥

**Comment by OriolAbril** [comment]
I believe this will address the branding comments @sethaxen. Feel free to add more libraries like PSIS.jl to the homepage, repeat the pattern but update icon/name/link. If you want to explore other icons to avoid repeating the julia one, you can browse them at https://icon-sets.iconify.design/

**Review by sethaxen — APPROVED** [review]
Looks great! I'll have to think about what a suitable icon for PSIS.jl would be; it shouldn't hold up this PR.

**Comment by OriolAbril** [comment]
We can merge, but I'd wait a bit before starting to use/advertise the site. We can discuss it a little bit on the meeting, but there are still several points to discuss:
* do we want to pair this "new website" with the new logo?
* and/or with custom domain?
* the citation section needs some work, is there a preferred (or any) way to cite the julia version? moreover in python we have the joss paper and a zenodo doi which can be version specific. 
* We also have some open issues, recurrent contributors and institutional partners that could be nice to address before that

**Comment by sethaxen** [comment]
>     * the citation section needs some work, is there a preferred (or any) way to cite the julia version? moreover in python we have the joss paper and a zenodo doi which can be version specific.
 
Not really. It might be worth writing an ArviZ.jl paper eventually, but not for a while (at least after it drops Python as a dependency). At the moment, it's probably best to cite the ArviZ paper and the ArviZ.jl repo both.

I could set up Zenodo DOIs for the repo, but I don't have a good sense for how useful that is wrt citing the repo and version, especially since archiving the repo would not archive also the version of Python ArviZ that is wrapped, which wouldn't make it any more reproducible.

Sure, we can discuss the other points in the meeting.

**Pull request merged**
